apps/pokemon/urls.py
from django.urls import include, path
from apps.pokemon.views import get_home, get_evolution_chain

urlpatterns = [
    path('api/', include(('apps.pokemon.urls_apis', 'api'), namespace='api')),
    path('', get_home, name='home'),
    path('home', get_home, name='home'),
    path('evolution-chain', get_evolution_chain, name='evolution-chain'),
]

pokedex/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.pokemon.urls', 'pokemon'), namespace='pokemon')),    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/pokemon/models.py
from django.db import models

# Create your models here.

class Pokemon(models.Model):
    pokeapi_id = models.IntegerField(primary_key = True)
    #General Information
    name = models.CharField(max_length = 100)
    height  = models.IntegerField()
    weight  = models.IntegerField()
    #Base Stats
    hp = models.IntegerField()
    attack  = models.IntegerField()
    special_attack  = models.IntegerField()
    deffense  = models.IntegerField()
    special_deffense  = models.IntegerField()
    speed  = models.IntegerField()
    #Image
    url_image = models.CharField(max_length = 255)

class Evolution(models.Model):
    pokeapi_id = models.IntegerField()
    evolves_from = models.ForeignKey(Pokemon, on_delete=models.PROTECT, related_name='evolves_from')
    evolves_to = models.ForeignKey(Pokemon, on_delete=models.PROTECT, related_name='evolves_to')
    class Meta:
        unique_together = ('evolves_from', 'evolves_to')

apps/pokemon/views.py
from django.db.models import Q
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from apps.pokemon.models import Pokemon, Evolution
import pandas as pd
import requests
import json

"""
Se declara una función recursiva que permitirá almacenar en las listas
pokemon_list y pokemon_chain_evolution la lista de pokemones y las cadenas
de evolución respectivamente.
Los parámetros de esta función son:
- pokemon_list / lista: En esta variable se almacena la lista de pokemones
- pokemon_chain_evolution: Es esta variable se almacena la cadena de evolución
    para los pokemones
- chain / diccionario: Este diccionario contiene las futuras evoluciones para 
    cada pokemon
- evolves_from / string: Esta variable almacena el nombre del pokemon para el
    cual se están consultando sus evoluciones

"""
def query_chain(pokemon_list, pokemon_chain_evolution, chain, evolves_from):
    #Se crea un diccionario para almacenar las propiedades del pokemon
    pokemon_data = {}
    pokemon_name = chain['species']['name']
    pokemon_data['name'] = pokemon_name
    #Se consulta la API para obtener las propiedades del pokemon y almacenarlas en pokemon_data
    pokemon_stats = requests.get('https://pokeapi.co/api/v2/pokemon/' + pokemon_name)
    pokemon_stats = pokemon_stats.json()
    pokemon_data['id'] = pokemon_stats['id']
    pokemon_data['hp'] = pokemon_stats['stats'][0]['base_stat']
    pokemon_data['attack'] = pokemon_stats['stats'][1]['base_stat']
    pokemon_data['special_attack'] = pokemon_stats['stats'][2]['base_stat']
    pokemon_data['deffense'] = pokemon_stats['stats'][3]['base_stat']
    pokemon_data['special_deffense'] = pokemon_stats['stats'][4]['base_stat']
    pokemon_data['speed'] = pokemon_stats['stats'][5]['base_stat']
    pokemon_data['height'] = pokemon_stats['height']*10 #Convertir a cm
    pokemon_data['weight'] = pokemon_stats['weight']*100 #Convertir a gramos
    pokemon_data['url_image'] = pokemon_stats['sprites']['front_default']
    #Se almacena el pokemon en pokemon_list
    pokemon_list.append(pokemon_data)
    #Se almacena el nombre del pokemon y su evolución
    pokemon_chain_evolution.append({'evolves_from':evolves_from, 'evolves_to':pokemon_name})
    pokemon_evolutions = chain['evolves_to']
    [query_chain(pokemon_list, pokemon_chain_evolution, pokemon_chain, pokemon_name) for pokemon_chain in pokemon_evolutions]
    return (pokemon_list, pokemon_chain_evolution)

def save_pokemon(pokemon_list):
    new_pokemon_list = []
    for pokemon in pokemon_list:
        pokemon_new = Pokemon()
        pokemon_new.pokeapi_id = int(pokemon['id'])
        pokemon_new.name = pokemon['name']
        pokemon_new.height = pokemon['height']
        pokemon_new.weight = pokemon['weight']
        pokemon_new.hp = pokemon['hp']
        pokemon_new.attack = pokemon['attack']
        pokemon_new.special_attack = pokemon['special_attack']
        pokemon_new.deffense = pokemon['deffense']
        pokemon_new.special_deffense = pokemon['special_deffense']
        pokemon_new.speed = pokemon['speed']
        pokemon_new.url_image = pokemon['url_image']
        new_pokemon_list.append(pokemon_new)
    Pokemon.objects.bulk_create(new_pokemon_list)
    return None

def save_pokemon_chain_evolution(evolution_chain_id, pokemon_chain_evolution, pokemon_list):
    evolution_list = []
    for evolution in pokemon_chain_evolution[1:]:
        evolution_new = Evolution()
        evolution_new.pokeapi_id = evolution_chain_id
        evolution_new.evolves_from_id = list(filter(lambda pokemon: pokemon['name'] == (evolution['evolves_from']), pokemon_list))[0]['id']
        evolution_new.evolves_to_id = list(filter(lambda pokemon: pokemon['name'] == (evolution['evolves_to']), pokemon_list))[0]['id']
        evolution_list.append(evolution_new)
    Evolution.objects.bulk_create(evolution_list)
    return None

def get_home(request):
    context = {}    
    return render (request, 'web/home.html', context)

def get_evolution_chain(request):
    pokemon_list = []
    context = {}
    if request.method == 'POST':
        evolution_chain_id = request.POST['evolution_chain_id']
        evolution_chain = requests.get('https://pokeapi.co/api/v2/evolution-chain/' + evolution_chain_id)
        evolution_chain = evolution_chain.json()
        chain = evolution_chain['chain']
        #Se instancia una lista vacía para almacenar los datos de los pokemones
        pokemon_list = list()
        #Se instancia una lista vacía para almacenar la cadena de evolución de los pokemones
        pokemon_chain_evolution = list()
        pokemon_list, pokemon_chain_evolution = query_chain(pokemon_list, pokemon_chain_evolution, chain, 0)
        #Se valida si la cadena de evolución ya está almacenada en DB, en caso que no se almacena
        #la cadena de evolución y los datos de cada uno de los pokemones que pertenecen a ella
        if Evolution.objects.filter(pokeapi_id = evolution_chain_id).count() == 0:
            save_pokemon(pokemon_list)
            save_pokemon_chain_evolution(evolution_chain_id, pokemon_chain_evolution, pokemon_list)
        context = {
            'query': True,
            'evolution_chain_id': evolution_chain_id,
            'pokemon_list': pokemon_list,
            'pokemon_chain_evolution': pokemon_chain_evolution,
        }
    return render (request, 'web/evolution_chain.html', context)

templates/web/evolution_chain.html
{% extends 'web/master.html' %}

{% block title %}Bienvenido{% endblock %}

{% load humanize %}

{% block content %}


    </div>
    
    <!-- stats -->
    <section class="w3_stats py-sm-5 py-4" id="stats">
        <div class="container">
            <div class="py-lg-5 w3-stats">
                <h2 class="w3pvt-title"><a href="{% url 'pokemon:home' %}"><span class="fa fa-angle-left" style="color: #d3b800;"></span></a> Explorar</h2>
                <p class="my-4 text-white">
                    Buscar cadenas de evolución
                </p>
                <div>
                    <form method="POST">
                        {% csrf_token %}
                        <input class="input-lg" type="number" min="1" max="475" placeholder="Ingresa un número" name="evolution_chain_id" value="{{evolution_chain_id}}" required>
                        <button class="btn btn-warning" type="submit">
                            <span class="fa fa-search"></span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- //stats -->
    <!-- pricing plans -->
    {% if query %}
    <section class="py-lg-5 py-4" id="plans">
        <div class="container py-md-5">
            <div class="title-desc text-center pb-sm-3">
                <h3 class="main-title-w3pvt">Resultados</h3>
                <p>Obtuvimos {{pokemon_list|length}} resultado(s):</p>
            </div>
            <div id="myDiagramDiv" style="width:100%; height:400px;">
            </div>
            <div class="row price-row">
                {% for pokemon in pokemon_list %}
                <div class="col-lg-4 col-sm-6 column mb-lg-5 mt-lg-3 mb-4">
                    <div class="box" data-blast="borderColor">
                        <div class="title">
                            <img src="{{pokemon.url_image}}">
                            <h5 data-blast="color">{{pokemon.name}} <sub>{{pokemon.id}}</sub></h5>
                        </div>
                        <div class="price">
                            <h6>{{pokemon.height}}cm / {{pokemon.weight|intcomma}}gr</h6>
                        </div>
                        <div class="option">
                            <ul>
                                <li>HP: {{pokemon.hp}}</li>
                                <li>Ataque: {{pokemon.attack}}</li>
                                <li>Ataque Especial: {{pokemon.special_attack}}</li>
                                <li>Defensa: {{pokemon.deffense}}</li>
                                <li>Defensa Especial: {{pokemon.special_deffense}}</li>
                                <li>Velocidad: {{pokemon.speed}}</li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
    <!-- //pricing plans -->
    
{% endblock %}

{% block scripts %}

<script>

//Se crea función para 'capitalizar' un string
const capitalize = (s) => {
    if (typeof s !== 'string') return ''
    return s.charAt(0).toUpperCase() + s.slice(1)
}

//Se instancia el gráfico, los nodos y los conectores
var $ = go.GraphObject.make;

var myDiagram =
    $(go.Diagram, "myDiagramDiv", {
        "undoManager.isEnabled": true,
        layout: $(go.TreeLayout, {
            angle: 90,
            layerSpacing: 35
        })
    });

myDiagram.nodeTemplate =
    $(go.Node, "Vertical",
        $(go.Picture, {
            margin: 5,
            width: 50,
            height: 50,
        },
        new go.Binding("source")),
        $(go.TextBlock, "Default Text", {
            margin: 12,
            stroke: "#d3b800",
            font: "bold 16px sans-serif"
        },
        new go.Binding("text", "name"))
    );

myDiagram.linkTemplate = $(go.Link, {
        routing: go.Link.Orthogonal,
        corner: 5
    },
    $(go.Shape, {
        strokeWidth: 3,
        stroke: "#e2e2e2" 
    })
);

var model = $(go.TreeModel);

myDiagram.model = model;

// Se crean variables para almacenar los datos de los pokemones y sus evoluciones

var pokemon_list = {{pokemon_list|safe}}
var pokemon_chain_evolution = {{pokemon_chain_evolution|safe}}

//Se agregan los nodos al gráfico

pokemon_chain_evolution.map((item, key) => {
    if(item.evolves_from == 0){
        myDiagram.model.addNodeData({
            'key': item.evolves_to,
            'name': capitalize(item.evolves_to),
            'source': pokemon_list.find(x => x.name == item.evolves_to).url_image
        })
    }
    else {
        myDiagram.model.addNodeData({
            'key': item.evolves_to,
            'parent': item.evolves_from,
            'name': capitalize(item.evolves_to),
            'source': pokemon_list.find(x => x.name == item.evolves_to).url_image
        })
    }
})

</script>

{% endblock %}

templates/web/master.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->

{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>PokeBook | {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="Pokedex" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Custom Theme files -->
    <link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet" media="all">
    <!-- color switch -->
    <link href="{% static 'css/blast.min.css' %}" rel="stylesheet" />
    <!-- portfolio -->
    <link href="{% static 'css/portfolio.css' %}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="all">
    <!-- font-awesome icons -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- online-fonts -->
    <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <script src="https://unpkg.com/gojs/release/go-debug.js"></script>
</head>

    {% block content %}

    {% endblock %}

    <!-- footer -->
    <footer class="cpy-right bg-theme" data-blast="bgColor">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="wthree-social">
                        <ul>
                            <li>
                                <a href="#">
                                    <span class="fa fa-facebook-f icon_facebook"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa fa-twitter icon_twitter"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa fa-google-plus icon_g_plus"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 text-lg-right mt-lg-0 mt-4">
                    <p>© 2018 Creature. All rights reserved | Design by
                        <a href="http://w3layouts.com"> W3layouts.</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- //footer -->
    <!-- // register -->
    <!-- js -->
    <script src="{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <!-- //js -->
    <!-- script for password match -->
    <script>
        window.onload = function () {
            document.getElementById("password1").onchange = validatePassword;
            document.getElementById("password2").onchange = validatePassword;
        }

        function validatePassword() {
            var pass2 = document.getElementById("password2").value;
            var pass1 = document.getElementById("password1").value;
            if (pass1 != pass2)
                document.getElementById("password2").setCustomValidity("Passwords Don't Match");
            else
                document.getElementById("password2").setCustomValidity('');
            //empty string means no validation error
        }
    </script>
    <!-- script for password match -->
    <!-- Banner  Responsiveslides -->
    <script src="{% static 'js/responsiveslides.min.js' %}"></script>
    <script>
        // You can also use"$(window).load(function() {"
        $(function () {
            // Slideshow 4
            $("#slider3").responsiveSlides({
                auto: true,
                pager: true,
                nav: false,
                speed: 500,
                namespace: "callbacks",
                before: function () {
                    $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                    $('.events').append("<li>after event fired.</li>");
                }
            });

        });
    </script>
    <!-- //Banner  Responsiveslides -->
    <!-- Scrolling Nav JavaScript -->
    <script src="{% static 'js/scrolling-nav.js' %}"></script>
    <script src="{% static 'js/counter.js' %}"></script>
    <!-- portfolio -->
    <script src="{% static 'js/jquery.picEyes.js' %}"></script>
    <script>
        $(function () {
            //picturesEyes($('.demo li'));
            $('.demo li').picEyes();
        });
    </script>
    <!-- //portfolio -->
    <!-- start-smooth-scrolling -->
    <script src="{% static 'js/move-top.js' %}"></script>
    <script src="{% static 'js/easing.js' %}"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();

                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 1000);
            });
        });
    </script>
    <!-- //end-smooth-scrolling -->
    <!-- smooth-scrolling-of-move-up -->
    <script>
        $(document).ready(function () {
            /*
            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear' 
            };
            */
            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <script src="{% static 'js/SmoothScroll.min.js' %}"></script>
    <!-- //smooth-scrolling-of-move-up -->
    <!-- color switch -->
    <script src="{% static 'js/blast.min.js' %}"></script>
    <!-- Bootstrap core JavaScript
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>

</html>